general:
  buildTool: "mta"
  mtaBuildTool: "cloudMbt"
  mtaSourcePath: "."

stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ11N20"

  malwareScan:
    scan: true

  acceptance: {}

  release: {}
