general:
  buildTool: "mta"
  mtaBuildTool: "cloudMbt"
  mtaSourcePath: "."

stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ11N20"

  additionalUnitTests:
    karmaExecuteTests: false
    npmExecuteScripts: false

  malwareScan:
    scan: true

  acceptance: {}

  release:
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "<YOUR_CF_ORG>"
    cfSpace: "<YOUR_CF_SPACE>"
